name: $(date:yyyyMMdd)$(rev:.r)

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  dotNetCoreVersion: 3.0.100-preview7-012821

jobs:
- job: windows
  displayName: Windows Build
  pool:
    vmImage: windows-2019
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK $(dotNetCoreVersion)
    inputs:
      version: $(dotNetCoreVersion)

  - powershell: ./build.ps1 --target=Restore-NuGet-Packages
    displayName: Prepare

  - powershell: ./build.ps1 --target=Build
    displayName: Build

  - powershell: ./build.ps1 --target=Test --test-filter="FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Windows"
    displayName: Test

- job: linux
  displayName: Linux Build
  dependsOn: windows
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core SDK $(dotNetCoreVersion)
    inputs:
      version: $(dotNetCoreVersion)

  - powershell: |
      echo "##vso[task.setvariable variable=sonarcloudUrl;]$(sonarcloud.url)"
      echo "##vso[task.setvariable variable=sonarcloudKey;]$(sonarcloud.key)"
      echo "##vso[task.setvariable variable=sonarcloudToken;]$(sonarcloud.token)"
      echo "##vso[task.setvariable variable=sonarcloudOrganization;]$(sonarcloud.organization)"
      echo "##vso[task.setvariable variable=nuGetSource;]$(feed.source)"
      echo "##vso[task.setvariable variable=nuGetApiKey;]$(feed.apikey)"
      # Stop local MySQL server, port is used for tests
      sudo systemctl stop mysql.service
    displayName: Set environment variables
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))

  - powershell: ./build.sh --target=Restore-NuGet-Packages
    displayName: Prepare

  - powershell: ./build.sh --target=Build
    displayName: Build

  - powershell: ./build.sh --target=Test
    displayName: Test

  - powershell: ./build.sh --target=Sonar
    displayName: Sonar
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))
    env:
      SONARQUBE_URL: $(sonarcloudUrl)
      SONARQUBE_KEY: $(sonarcloudKey)
      SONARQUBE_TOKEN: $(sonarcloudToken)
      SONARQUBE_ORGANIZATION: $(sonarcloudOrganization)

  - powershell: ./build.sh --target=Publish
    displayName: Publish
    condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))
    env:
      NUGET_SOURCE: $(nuGetSource)
      NUGET_APIKEY: $(nuGetApiKey)
